"""Add must_logout to User

Revision ID: 06d5692cdb19
Revises: 51047d7a6ded
Create Date: 2026-02-16 08:20:41.687105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d5692cdb19'
down_revision = '51047d7a6ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_logout', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_logout')

    # ### end Alembic commands ###
