"""Add presence fields to User

Revision ID: 3aa12d0d0085
Revises: 32a9308f21b9
Create Date: 2026-01-22 16:24:47.120996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa12d0d0085'
down_revision = '32a9308f21b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_focus_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_focus_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_focus_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_current_task_id', 'task', ['current_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_task_id')
        batch_op.drop_column('current_focus_mode')
        batch_op.drop_column('current_focus_end')
        batch_op.drop_column('current_focus_start')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
