"""Add profile_pic_url and bio to user

Revision ID: 49604e82a442
Revises: fe3157e11acd
Create Date: 2026-02-05 10:04:59.521946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49604e82a442'
down_revision = 'fe3157e11acd'
branch_labels = None
depends_on = None


def upgrade():
    # Direct check for columns to avoid DuplicateColumn errors in production
    conn = op.get_bind()
    
    # Check for profile_pic_url
    res_url = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='user' AND column_name='profile_pic_url'")).fetchone()
    if not res_url:
        op.add_column('user', sa.Column('profile_pic_url', sa.String(length=500), nullable=True))
    
    # Check for bio
    res_bio = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='user' AND column_name='bio'")).fetchone()
    if not res_bio:
        op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_pic_url')

    # ### end Alembic commands ###
