"""Add is_admin and is_banned to user

Revision ID: 51047d7a6ded
Revises: 627eb9f28936
Create Date: 2026-02-05 10:28:28.399701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51047d7a6ded'
down_revision = '627eb9f28936'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('user')]
    
    if 'is_admin' not in columns:
        op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
        op.execute("UPDATE \"user\" SET is_admin = False WHERE is_admin IS NULL")
    
    if 'is_banned' not in columns:
        op.add_column('user', sa.Column('is_banned', sa.Boolean(), nullable=True))
        op.execute("UPDATE \"user\" SET is_banned = False WHERE is_banned IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_banned')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
