"""Add profile_pic_position to user

Revision ID: 627eb9f28936
Revises: 49604e82a442
Create Date: 2026-02-05 10:09:47.837917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627eb9f28936'
down_revision = '49604e82a442'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    res_pos = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='user' AND column_name='profile_pic_position'")).fetchone()
    if not res_pos:
        op.add_column('user', sa.Column('profile_pic_position', sa.String(length=20), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_position')

    # ### end Alembic commands ###
