"""Add timer settings

Revision ID: 6586067595fd
Revises: 848ef3f6f393
Create Date: 2026-01-08 09:45:40.002447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6586067595fd'
down_revision = '848ef3f6f393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_start_break', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_start_focus', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_start_focus')
        batch_op.drop_column('auto_start_break')

    # ### end Alembic commands ###
