"""add recurrence_days to event

Revision ID: 7ce5b5572dd6
Revises: 8b4ee7aad4b1
Create Date: 2026-01-12 18:16:28.854481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce5b5572dd6'
down_revision = '8b4ee7aad4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_days', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('recurrence_days')

    # ### end Alembic commands ###
