"""Add accent_color

Revision ID: 8b4ee7aad4b1
Revises: e60e1a51dd97
Create Date: 2026-01-12 18:02:51.128161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4ee7aad4b1'
down_revision = 'e60e1a51dd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accent_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accent_color')

    # ### end Alembic commands ###
