"""Add timer duration settings

Revision ID: 90a32df50f7f
Revises: 15c8f80e4655
Create Date: 2026-01-09 15:21:31.878463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a32df50f7f'
down_revision = '15c8f80e4655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('break_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('break_duration')
        batch_op.drop_column('focus_duration')

    # ### end Alembic commands ###
