"""Add sync settings to StudyRoom

Revision ID: 9659800ed178
Revises: 3aa12d0d0085
Create Date: 2026-01-22 16:28:14.758201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9659800ed178'
down_revision = '3aa12d0d0085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('break_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sessions_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.drop_column('sessions_count')
        batch_op.drop_column('break_duration')
        batch_op.drop_column('focus_duration')

    # ### end Alembic commands ###
