"""add trmnl fields to user and task

Revision ID: abbdf470f035
Revises: 448c213c5d36
Create Date: 2026-02-28 18:05:23.708225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbdf470f035'
down_revision = '448c213c5d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned_to_trmnl', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_trmnl_poll', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_trmnl_poll')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_pinned_to_trmnl')

    # ### end Alembic commands ###
