"""Add active state to StudyRoom

Revision ID: b8ce3ee18593
Revises: 9659800ed178
Create Date: 2026-01-22 16:46:10.645691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ce3ee18593'
down_revision = '9659800ed178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('active_start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.drop_column('active_start_time')
        batch_op.drop_column('active_mode')

    # ### end Alembic commands ###
