"""Add seconds_remaining to StudyRoom

Revision ID: d62671cebe34
Revises: b8ce3ee18593
Create Date: 2026-01-22 16:46:40.837274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62671cebe34'
down_revision = 'b8ce3ee18593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seconds_remaining', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_room', schema=None) as batch_op:
        batch_op.drop_column('seconds_remaining')

    # ### end Alembic commands ###
