"""Add Notification model and settings

Revision ID: e60e1a51dd97
Revises: f2929e536248
Create Date: 2026-01-12 17:54:43.938071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60e1a51dd97'
down_revision = 'f2929e536248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_pomodoro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_event_start', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('event_notify_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('event_notify_minutes')
        batch_op.drop_column('notify_event_start')
        batch_op.drop_column('notify_pomodoro')

    op.drop_table('notification')
    # ### end Alembic commands ###
