"""add partner_id to focus_session

Revision ID: f2374eb8a7e0
Revises: 50874160757b
Create Date: 2026-01-24 10:29:55.733153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2374eb8a7e0'
down_revision = '50874160757b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focus_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_focus_session_partner_id_user', 'user', ['partner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focus_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_focus_session_partner_id_user', type_='foreignkey')
        batch_op.drop_column('partner_id')

    # ### end Alembic commands ###
