"""add_performance_indexes

Revision ID: fb1a573ea24e
Revises: 06d5692cdb19
Create Date: 2026-02-16 12:49:14.786847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1a573ea24e'
down_revision = '06d5692cdb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_completion_date'), ['date'], unique=False)

    with op.batch_alter_table('focus_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_session_date'), ['date'], unique=False)

    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_completion_date'), ['date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_last_seen'), ['last_seen'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_last_seen'))

    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_completion_date'))

    with op.batch_alter_table('focus_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_session_date'))

    with op.batch_alter_table('event_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_completion_date'))

    # ### end Alembic commands ###
