"""Add last_focus_end to User

Revision ID: fe3157e11acd
Revises: fdbb13ae7f30
Create Date: 2026-02-02 14:23:24.365225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3157e11acd'
down_revision = 'fdbb13ae7f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_focus_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_focus_end')

    # ### end Alembic commands ###
